server:
  port: 9998

#注册中心
eureka:
  client:
    #设置服务注册中心的URL
    service-url:
      # 这个地址必须得对
      defaultZone: http://localhost:8500/eureka/

#设置服务名称
spring:
  application:
    name: yuk-test-eureka-client-as-consumer-fegin